// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNiZCiSuiem4vlQzUXK7s1r4l-Ccnm15w',
    appId: '1:894503455701:web:ae1dbf23cdf58bcd0b0b5c',
    messagingSenderId: '894503455701',
    projectId: 'sparkup-6b9ad',
    authDomain: 'sparkup-6b9ad.firebaseapp.com',
    storageBucket: 'sparkup-6b9ad.firebasestorage.app',
    measurementId: 'G-E090EGLW2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl1GeLR_-JVWO1zzQWosd3Qimv1A-4f6E',
    appId: '1:894503455701:android:615e7579f9563e970b0b5c',
    messagingSenderId: '894503455701',
    projectId: 'sparkup-6b9ad',
    storageBucket: 'sparkup-6b9ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXfDqLPEaPJXqg-YCqYsoBy4GodFCDsw',
    appId: '1:894503455701:ios:c94b17c63b59012d0b0b5c',
    messagingSenderId: '894503455701',
    projectId: 'sparkup-6b9ad',
    storageBucket: 'sparkup-6b9ad.firebasestorage.app',
    androidClientId: '894503455701-16hiv3r63s1tqcg98r5o3d1rm2ucfpom.apps.googleusercontent.com',
    iosClientId: '894503455701-vth3po63emf77qm9vaqv4q7itfu9gcsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXfDqLPEaPJXqg-YCqYsoBy4GodFCDsw',
    appId: '1:894503455701:ios:c94b17c63b59012d0b0b5c',
    messagingSenderId: '894503455701',
    projectId: 'sparkup-6b9ad',
    storageBucket: 'sparkup-6b9ad.firebasestorage.app',
    androidClientId: '894503455701-16hiv3r63s1tqcg98r5o3d1rm2ucfpom.apps.googleusercontent.com',
    iosClientId: '894503455701-vth3po63emf77qm9vaqv4q7itfu9gcsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNiZCiSuiem4vlQzUXK7s1r4l-Ccnm15w',
    appId: '1:894503455701:web:6ab24175496a35b00b0b5c',
    messagingSenderId: '894503455701',
    projectId: 'sparkup-6b9ad',
    authDomain: 'sparkup-6b9ad.firebaseapp.com',
    storageBucket: 'sparkup-6b9ad.firebasestorage.app',
    measurementId: 'G-WQ8WYVY6G1',
  );

}